travis:
  secure:
    BINSTAR_TOKEN: LBICwvtQGHz/oOubVJyAZM6Xe168lbt7g//grFp2uMId74vVwHSrX7P5zUQBv9Bqmb/1LsvpOFMhuilqxmrWmzBKV6cBSQJSZPxPtYYmI85hgcvpvXM8UtR8zo7dlapEdvbBbMpO7pB/xuS4bUbIKlz8GOd5DU3CYeZvcAz8Pbex06rGJmyFokNmWPWkh/s8KCFCKjxszllLtFxJwPjeQ8twRvGlvKB9cEQrsBizX7RZsPTeyri0IHWmZH3gv9t9j3A7jnRl8OvFPP4gbVoimMFhgScqJIbpr/8UMKle26EI0gzZsWfpCQNZeb2nlb8Vt/GRp8qERALKh4cr4xMZcp0/moHf3DYnyL9vRXj+KNGMCNZcp9FVWyvI3AHVPfXC6wTJs/N38uJcdksGlAwr2QLKv+2JoS++yflpYzUDeS7ysQzC6Hj3yCRR3PNOL23I3o9TZBrFzXTdbwmsrkzmY3N6UDKq7OiqJwNQkxxv762vkIMql+ZPvPha0lnYpzvh7dwiLkul2y3VpcVVwi8LaCmxSpyKBByNpE0zBdEAFEhLUE0Yk0wU/45hPm3a8w9uRkkZ1qffV/twNIsJZzVIUlnzFDQdtmyIGdErL1Bs3T/ZoP69n8uU0VGMckCggWY5EE669s9sMwtkWyhgRCX+u8lstR7b1x6Qdnay6W2vW5Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
